@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name signup
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "name": "user-teste",
  "email": "teste@email.com",
  "password": "123456",
  "birthDate": "1990-12-03",
  "balance": 120.05
}


###

# @name authenticate
POST {{baseUrl}}/users/signin
Content-Type: application/json

{
  "email": "joao.silva@example.com",
  "password": "senha123"
}

###

# @name transfer
POST {{baseUrl}}/transfer
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "fromId": "750b3075-4736-414d-b5cd-3555619ff72b",
  "toId": "363fd8b0-d990-4dba-960e-e66eaaaf0c43",
  "amount": 20.00
}

###

# @name getAllUsers
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

